#ifdef DYN_DEBUG

#include "DbgPrint.h"

extern char op_str[100];

void DBGPrint_RT_IMM()
{
	DBGPRINT_RT_IMM
}

void DBGPrint_RT_FS(uint32 X)
{
	DBGPRINT_RT_FS(X)
}

void DBGPrint_BASE_RT_OFFSET() 
{
	DBGPRINT_BASE_RT_OFFSET
}

void DBGPrint_RS_RT_IMM() 
{
	DBGPRINT_RS_RT_IMM
}
										
void DBGPrint_RS_RT_IMMH() 
{
	DBGPRINT_RS_RT_IMMH
}

void DBGPrint_RS_OFF() 
{
	DBGPRINT_RS_OFF		
}

void DBGPrint_RS_IMM()
{
	DBGPRINT_RS_IMM
}

void DBGPrint_RS_RD()
{ 
	DBGPRINT_RS_RD
}

void DBGPrint_RS_RT_RD()
{ 
	DBGPRINT_RS_RT_RD
}

void DBGPrint_RT_RD_SA()
{ 
	DBGPRINT_RT_RD_SA
}

void DBGPrint_RS_RT()
{ 
	DBGPRINT_RS_RT
}

void DBGPrint_RD()	
{ 
	DBGPRINT_RD
}

void DBGPrint_RS()
{ 
	DBGPRINT_RS
}

void DBGPrint_RS_RT_OFF()
{ 
	DBGPRINT_RS_RT_OFF
}

void DBGPrint_RS_RT_OFF_BRANCH()
{ 
	DBGPRINT_RS_RT_OFF_BRANCH
}

void DBGPrint_INSTR_INDEX()
{	
	DBGPRINT_INSTR_INDEX
}

void DBGPrint_RT_RD_RS()
{ 
	DBGPRINT_RT_RD_RS
}

void DBGPrint_CACHE()
{	
	DBGPRINT_CACHE
}
  
void DBGPrint_BASE_RT_OFFS_COP0()
{ 
	DBGPRINT_BASE_RT_OFFS_COP0
}

	#define DYN_DBGPRINT_BASE_RT_OFFSET		C_CALL( Dest, DBGPrint_BASE_RT_OFFSET )
	#define DYN_DBGPRINT_RT_FS(X)			C_CALL( Dest, DBGPrint_RT_FS )
	#define DYN_DBGPRINT_RT_IMM				C_CALL( Dest, DBGPrint_RT_IMM )
	#define DYN_DBGPRINT_RT_RD_RS			C_CALL( Dest, DBGPrint_RT_RD_RS )	
	#define DYN_DBGPRINT_RS_RT_IMM			C_CALL( Dest, DBGPrint_RS_RT_IMM )
	#define DYN_DBGPRINT_RS_RT_IMMH			C_CALL( Dest, DBGPrint_RS_RT_IMMH	)		
	#define DYN_DBGPRINT_RS_OFF				C_CALL( Dest, DBGPrint_RS_OFF )
	#define DYN_DBGPRINT_RS_IMM				C_CALL( Dest, DBGPrint_RS_IMM )
	#define DYN_DBGPRINT_RS_RD				C_CALL( Dest, DBGPrint_RS_RD )
	#define DYN_DBGPRINT_RS_RT_RD			C_CALL( Dest, DBGPrint_RS_RT_RD )
	#define DYN_DBGPRINT_RT_RD_SA			C_CALL( Dest, DBGPrint_RT_RD_SA )
	#define DYN_DBGPRINT_RS_RT				C_CALL( Dest, DBGPrint_RS_RT )
	#define DYN_DBGPRINT_RD					C_CALL( Dest, DBGPrint_RD )
	#define DYN_DBGPRINT_RS					C_CALL( Dest, DBGPrint_RS	)
	#define DYN_DBGPRINT_RS_RT_OFF			C_CALL( Dest, DBGPrint_RS_RT_OFF )
	#define DYN_DBGPRINT_RS_RT_OFF_BRANCH	C_CALL( Dest, DBGPrint_RS_RT_OFF_BRANCH )
	#define	DYN_DBGPRINT_INSTR_INDEX		C_CALL(	Dest, DBGPrint_INSTR_INDEX )
	#define DYN_DBGPRINT_CACHE				C_CALL( Dest, DBGPrint_CACHE )
	#define DYN_DBGPRINT_BASE_RT_OFFS_COP0	C_CALL( Dest, DBGPrint_BASE_RT_OFFS_COP0 )


#else
	#define DYN_DBGPRINT_BASE_RT_OFFSET
	#define DYN_DBGPRINT_RT_FS(X)
	#define DYN_DBGPRINT_RT_IMM
	#define DYN_DBGPRINT_RT_RD_RS	
	#define DYN_DBGPRINT_RS_RT_IMM
	#define DYN_DBGPRINT_RS_RT_IMMH			
	#define DYN_DBGPRINT_RS_OFF
	#define DYN_DBGPRINT_RS_IMM
	#define DYN_DBGPRINT_RS_RD
	#define DYN_DBGPRINT_RS_RT_RD
	#define DYN_DBGPRINT_RT_RD_SA
	#define DYN_DBGPRINT_RS_RT
	#define DYN_DBGPRINT_RD
	#define DYN_DBGPRINT_RS	
	#define DYN_DBGPRINT_RS_RT_OFF
	#define DYN_DBGPRINT_RS_RT_OFF_BRANCH
	#define	DYN_DBGPRINT_INSTR_INDEX
	#define DYN_DBGPRINT_CACHE
	#define DYN_DBGPRINT_BASE_RT_OFFS_COP0
#endif
